name: Daily Email Service Scraper

on:
  schedule:
    - cron: '0 6 * * *'  # Daily at 6 AM UTC
  workflow_dispatch:      # Manual trigger only
  # DO NOT include push trigger - it causes conflicts

permissions:
  contents: write

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Run scraper
        run: node scraper.js
      
      - name: Show generated data
        run: |
          echo "Generated data.json:"
          head -20 data.json
      
      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git pull origin main --rebase || true
          git add data.json
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update pricing data [automated]"
            git push origin main
          fi
