name: Daily Email Service Scraper

on:
  schedule:
    - cron: '0 6 * * *'  # Runs daily at 6 AM UTC
  workflow_dispatch:  # Allows manual triggering
  push:
    branches: [main]  # Also runs on push for testing

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm install puppeteer-core cheerio axios chromium
      
      - name: Run scraper
        run: node scraper.js
        env:
          PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium
      
      - name: Commit updated data
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add data.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update pricing data [automated]" && git push)
