name: Daily Email Service Scraper

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write  # This is the key line!

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Run scraper
        run: node scraper.js
      
      - name: Show generated data
        run: |
          echo "Generated data.json:"
          cat data.json
      
      - name: Commit updated data
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add data.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update pricing data [automated]" && git push)
